excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://KevinBinon.github.io
title: Kevin Binon
tagline: Gaming is better than chocolate
description: Life as a java dev && gamer
paginate: 5
gems: [jekyll-paginate]